name: AUR
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - name: Install tools
        run: pacman -Syu --needed --noconfirm openssh git

      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_KEY }}

      - name: Add AUR to known_hosts
        run: mkdir -p /etc/ssh/ && echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> /etc/ssh/ssh_known_hosts

      - name: Checkout AUR repo
        run: git clone ssh://aur@aur.archlinux.org/alvr.git aur/

      - name: Replace PKGBUILD
        run: cat PKGBUILD > aur/PKGBUILD

      - name: Check if anything changed
        run: "! git diff-index --exit-code --quiet HEAD"
        working-directory: ./aur

      - name: Install dev tools
        run: pacman -S --needed --noconfirm base-devel namcap

      - name: Setup
        run: |
          chgrp nobody aur/
          chmod g+ws aur/
          setfacl -m u::rwx,g::rwx aur/
          setfacl -d --set u::rwx,g::rwx,o::- aur/
          echo "nobody ALL = NOPASSWD: /usr/bin/pacman" > /etc/sudoers.d/nobody-pacman

      - name: Build package
        working-directory: ./aur
        run: sudo -E -u nobody makepkg --noconfirm -s && sudo -u nobody makepkg --printsrcinfo > .SRCINFO
        env:
          HOME: ${{ github.workspace }}/aur/

      - name: Validate package
        working-directory: ./aur
        run: namcap PKGBUILD && namcap *.pkg*

      - name: Commit
        working-directory: ./aur
        run: |
          source $GITHUB_WORKSPACE/PKGBUILD
          git config --global user.email "you@example.com"
          git config --global user.name "ALVR Bot"
          git commit --author "ALVR Bot <>" -am "[CI] ALVR $pkgver-$pkgrel"
          git push
