name: AUR
on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - name: Install tools
        run: pacman -Syu --noconfirm base-devel namcap openssh git

      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_KEY }}

      - name: Checkout AUR repo
        run: git clone ssh://aur@aur.archlinux.org/alvr.git aur/

      - name: Replace PKGBUILD
        run: cat PKGBUILD > aur/PKGBUILD

      - name: Check if anything changed
        run: cd aur/ && git diff-index --quiet HEAD

      - name: Setup
        run: |
          chgrp nobody aur/
          chmod g+ws aur/
          setfacl -m u::rwx,g::rwx aur/
          setfacl -d --set u::rwx,g::rwx,o::- aur/
          echo "nobody ALL = NOPASSWD: /usr/bin/pacman" > /etc/sudoers.d/nobody-pacman

      - name: Build package
        run: cd aur/ && sudo -u nobody makepkg --printsrcinfo > .SRCINFO && sudo -u nobody makepkg -s

      - name: Validate package
        run: cd aur/ && namcap PKGBUILD && namcap *.pkg*
